name: Deploy app to Heroku
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    
    - uses: actions/checkout@v2

    - name: Checkout secrets repo
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.SECRETS_REPO }}
        token: ${{ secrets.SECRETS_REPO_ACCESS_TOKEN }}
        path: secrets
   
    - name: Build and deploy the Docker image
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'google-cloud-task-processor' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
